# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceteam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spaceteam.proto',
  package='',
  syntax='proto2',
  serialized_options=_b('\n\005protoB\017TcpPacketProtos'),
  serialized_pb=_b('\n\x0fspaceteam.proto\"\xa1\x04\n\x0fSpaceteamPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x1a\xb2\x01\n\x0fGameStatePacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x12\x14\n\x0cplayer_count\x18\x02 \x01(\x05\x12\x37\n\x06update\x18\x03 \x02(\x0e\x32\'.SpaceteamPacket.GameStatePacket.Update\"%\n\x06Update\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\x0e\n\nDISCONNECT\x10\x01\x1aL\n\rConnectPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x12\x10\n\x08lobby_id\x18\x02 \x02(\t\x1a[\n\x0bReadyPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x12\x0e\n\x06toggle\x18\x02 \x02(\x08\x12\x11\n\tplayer_id\x18\x03 \x01(\t\x1a=\n\x10\x44isconnectPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\"D\n\nPacketType\x12\x0e\n\nGAME_STATE\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0e\n\nDISCONNECT\x10\x03\x42\x18\n\x05protoB\x0fTcpPacketProtos')
)



_SPACETEAMPACKET_GAMESTATEPACKET_UPDATE = _descriptor.EnumDescriptor(
  name='Update',
  full_name='SpaceteamPacket.GameStatePacket.Update',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=224,
  serialized_end=261,
)
_sym_db.RegisterEnumDescriptor(_SPACETEAMPACKET_GAMESTATEPACKET_UPDATE)

_SPACETEAMPACKET_PACKETTYPE = _descriptor.EnumDescriptor(
  name='PacketType',
  full_name='SpaceteamPacket.PacketType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GAME_STATE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=497,
  serialized_end=565,
)
_sym_db.RegisterEnumDescriptor(_SPACETEAMPACKET_PACKETTYPE)


_SPACETEAMPACKET_GAMESTATEPACKET = _descriptor.Descriptor(
  name='GameStatePacket',
  full_name='SpaceteamPacket.GameStatePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.GameStatePacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_count', full_name='SpaceteamPacket.GameStatePacket.player_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update', full_name='SpaceteamPacket.GameStatePacket.update', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPACETEAMPACKET_GAMESTATEPACKET_UPDATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=261,
)

_SPACETEAMPACKET_CONNECTPACKET = _descriptor.Descriptor(
  name='ConnectPacket',
  full_name='SpaceteamPacket.ConnectPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.ConnectPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lobby_id', full_name='SpaceteamPacket.ConnectPacket.lobby_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=339,
)

_SPACETEAMPACKET_READYPACKET = _descriptor.Descriptor(
  name='ReadyPacket',
  full_name='SpaceteamPacket.ReadyPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.ReadyPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toggle', full_name='SpaceteamPacket.ReadyPacket.toggle', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='SpaceteamPacket.ReadyPacket.player_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=432,
)

_SPACETEAMPACKET_DISCONNECTPACKET = _descriptor.Descriptor(
  name='DisconnectPacket',
  full_name='SpaceteamPacket.DisconnectPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.DisconnectPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=495,
)

_SPACETEAMPACKET = _descriptor.Descriptor(
  name='SpaceteamPacket',
  full_name='SpaceteamPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SPACETEAMPACKET_GAMESTATEPACKET, _SPACETEAMPACKET_CONNECTPACKET, _SPACETEAMPACKET_READYPACKET, _SPACETEAMPACKET_DISCONNECTPACKET, ],
  enum_types=[
    _SPACETEAMPACKET_PACKETTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=565,
)

_SPACETEAMPACKET_GAMESTATEPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_GAMESTATEPACKET.fields_by_name['update'].enum_type = _SPACETEAMPACKET_GAMESTATEPACKET_UPDATE
_SPACETEAMPACKET_GAMESTATEPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET_GAMESTATEPACKET_UPDATE.containing_type = _SPACETEAMPACKET_GAMESTATEPACKET
_SPACETEAMPACKET_CONNECTPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_CONNECTPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET_READYPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_READYPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET_DISCONNECTPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_DISCONNECTPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_PACKETTYPE.containing_type = _SPACETEAMPACKET
DESCRIPTOR.message_types_by_name['SpaceteamPacket'] = _SPACETEAMPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpaceteamPacket = _reflection.GeneratedProtocolMessageType('SpaceteamPacket', (_message.Message,), dict(

  GameStatePacket = _reflection.GeneratedProtocolMessageType('GameStatePacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_GAMESTATEPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.GameStatePacket)
    ))
  ,

  ConnectPacket = _reflection.GeneratedProtocolMessageType('ConnectPacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_CONNECTPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.ConnectPacket)
    ))
  ,

  ReadyPacket = _reflection.GeneratedProtocolMessageType('ReadyPacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_READYPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.ReadyPacket)
    ))
  ,

  DisconnectPacket = _reflection.GeneratedProtocolMessageType('DisconnectPacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_DISCONNECTPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.DisconnectPacket)
    ))
  ,
  DESCRIPTOR = _SPACETEAMPACKET,
  __module__ = 'spaceteam_pb2'
  # @@protoc_insertion_point(class_scope:SpaceteamPacket)
  ))
_sym_db.RegisterMessage(SpaceteamPacket)
_sym_db.RegisterMessage(SpaceteamPacket.GameStatePacket)
_sym_db.RegisterMessage(SpaceteamPacket.ConnectPacket)
_sym_db.RegisterMessage(SpaceteamPacket.ReadyPacket)
_sym_db.RegisterMessage(SpaceteamPacket.DisconnectPacket)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
