# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import player_pb2 as player__pb2
import level_pb2 as level__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ngame.proto\x1a\x0cplayer.proto\x1a\x0blevel.proto\"i\n\x04Game\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04life\x18\x02 \x02(\x05\x12\x15\n\x05level\x18\x03 \x02(\x0b\x32\x06.Level\x12\x12\n\nmaxPlayers\x18\x04 \x02(\x05\x12\x1c\n\x0bplayer_list\x18\x05 \x03(\x0b\x32\x07.PlayerB\x13\n\x05protoB\nGameProtos')
  ,
  dependencies=[player__pb2.DESCRIPTOR,level__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Game.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='life', full_name='Game.life', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Game.level', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxPlayers', full_name='Game.maxPlayers', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_list', full_name='Game.player_list', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=146,
)

_GAME.fields_by_name['level'].message_type = level__pb2._LEVEL
_GAME.fields_by_name['player_list'].message_type = player__pb2._PLAYER
DESCRIPTOR.message_types_by_name['Game'] = _GAME

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), dict(
  DESCRIPTOR = _GAME,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:Game)
  ))
_sym_db.RegisterMessage(Game)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005protoB\nGameProtos'))
# @@protoc_insertion_point(module_scope)
