# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: level.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tool_pb2 as tool__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='level.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0blevel.proto\x1a\ntool.proto\"Q\n\x05Level\x12\n\n\x02id\x18\x01 \x02(\t\x12\r\n\x05level\x18\x02 \x02(\x05\x12\x13\n\x0b\x63\x61pCommands\x18\x03 \x02(\x05\x12\x18\n\ttool_list\x18\x04 \x03(\x0b\x32\x05.ToolB\x14\n\x05protoB\x0bLevelProtos')
  ,
  dependencies=[tool__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LEVEL = _descriptor.Descriptor(
  name='Level',
  full_name='Level',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Level.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Level.level', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='capCommands', full_name='Level.capCommands', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tool_list', full_name='Level.tool_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=108,
)

_LEVEL.fields_by_name['tool_list'].message_type = tool__pb2._TOOL
DESCRIPTOR.message_types_by_name['Level'] = _LEVEL

Level = _reflection.GeneratedProtocolMessageType('Level', (_message.Message,), dict(
  DESCRIPTOR = _LEVEL,
  __module__ = 'level_pb2'
  # @@protoc_insertion_point(class_scope:Level)
  ))
_sym_db.RegisterMessage(Level)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005protoB\013LevelProtos'))
# @@protoc_insertion_point(module_scope)
