# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: panel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='panel.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bpanel.proto\"2\n\x05Panel\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0f\n\x07tool_id\x18\x03 \x02(\tB\x14\n\x05protoB\x0bPanelProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PANEL = _descriptor.Descriptor(
  name='Panel',
  full_name='Panel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Panel.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Panel.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tool_id', full_name='Panel.tool_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['Panel'] = _PANEL

Panel = _reflection.GeneratedProtocolMessageType('Panel', (_message.Message,), dict(
  DESCRIPTOR = _PANEL,
  __module__ = 'panel_pb2'
  # @@protoc_insertion_point(class_scope:Panel)
  ))
_sym_db.RegisterMessage(Panel)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005protoB\013PanelProtos'))
# @@protoc_insertion_point(module_scope)
