# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceteam.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spaceteam.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fspaceteam.proto\"\xbd\x06\n\x0fSpaceteamPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x1a\xe5\x02\n\x0fGameStatePacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x12\x14\n\x0cplayer_count\x18\x02 \x01(\x05\x12\x0e\n\x06sector\x18\x03 \x01(\x05\x12\r\n\x05\x63lock\x18\x04 \x01(\x05\x12\x37\n\x06update\x18\x05 \x02(\x0e\x32\'.SpaceteamPacket.GameStatePacket.Update\x12\x37\n\x06screen\x18\x06 \x01(\x0e\x32\'.SpaceteamPacket.GameStatePacket.Screen\"A\n\x06Update\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\x0e\n\nDISCONNECT\x10\x01\x12\n\n\x06SECTOR\x10\x02\x12\x0e\n\nCLOCK_TICK\x10\x03\"=\n\x06Screen\x12\t\n\x05LOBBY\x10\x00\x12\x0f\n\x0bSECTOR_WAIT\x10\x01\x12\r\n\tSHIP_WAIT\x10\x02\x12\x08\n\x04SHIP\x10\x03\x1aL\n\rConnectPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x12\x10\n\x08lobby_id\x18\x02 \x02(\t\x1a[\n\x0bReadyPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x12\x0e\n\x06toggle\x18\x02 \x02(\x08\x12\x11\n\tplayer_id\x18\x03 \x01(\t\x1a=\n\x10\x44isconnectPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x1aZ\n\rCommandPacket\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.SpaceteamPacket.PacketType\x12\r\n\x05panel\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x02(\t\"Q\n\nPacketType\x12\x0e\n\nGAME_STATE\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\t\n\x05READY\x10\x02\x12\x0e\n\nDISCONNECT\x10\x03\x12\x0b\n\x07\x43OMMAND\x10\x04\x42\x18\n\x05protoB\x0fTcpPacketProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SPACETEAMPACKET_GAMESTATEPACKET_UPDATE = _descriptor.EnumDescriptor(
  name='Update',
  full_name='SpaceteamPacket.GameStatePacket.Update',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTOR', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOCK_TICK', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=312,
  serialized_end=377,
)
_sym_db.RegisterEnumDescriptor(_SPACETEAMPACKET_GAMESTATEPACKET_UPDATE)

_SPACETEAMPACKET_GAMESTATEPACKET_SCREEN = _descriptor.EnumDescriptor(
  name='Screen',
  full_name='SpaceteamPacket.GameStatePacket.Screen',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOBBY', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SECTOR_WAIT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHIP_WAIT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHIP', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=379,
  serialized_end=440,
)
_sym_db.RegisterEnumDescriptor(_SPACETEAMPACKET_GAMESTATEPACKET_SCREEN)

_SPACETEAMPACKET_PACKETTYPE = _descriptor.EnumDescriptor(
  name='PacketType',
  full_name='SpaceteamPacket.PacketType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GAME_STATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=768,
  serialized_end=849,
)
_sym_db.RegisterEnumDescriptor(_SPACETEAMPACKET_PACKETTYPE)


_SPACETEAMPACKET_GAMESTATEPACKET = _descriptor.Descriptor(
  name='GameStatePacket',
  full_name='SpaceteamPacket.GameStatePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.GameStatePacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_count', full_name='SpaceteamPacket.GameStatePacket.player_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sector', full_name='SpaceteamPacket.GameStatePacket.sector', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clock', full_name='SpaceteamPacket.GameStatePacket.clock', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='update', full_name='SpaceteamPacket.GameStatePacket.update', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='screen', full_name='SpaceteamPacket.GameStatePacket.screen', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPACETEAMPACKET_GAMESTATEPACKET_UPDATE,
    _SPACETEAMPACKET_GAMESTATEPACKET_SCREEN,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=440,
)

_SPACETEAMPACKET_CONNECTPACKET = _descriptor.Descriptor(
  name='ConnectPacket',
  full_name='SpaceteamPacket.ConnectPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.ConnectPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lobby_id', full_name='SpaceteamPacket.ConnectPacket.lobby_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=442,
  serialized_end=518,
)

_SPACETEAMPACKET_READYPACKET = _descriptor.Descriptor(
  name='ReadyPacket',
  full_name='SpaceteamPacket.ReadyPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.ReadyPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toggle', full_name='SpaceteamPacket.ReadyPacket.toggle', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='SpaceteamPacket.ReadyPacket.player_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=520,
  serialized_end=611,
)

_SPACETEAMPACKET_DISCONNECTPACKET = _descriptor.Descriptor(
  name='DisconnectPacket',
  full_name='SpaceteamPacket.DisconnectPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.DisconnectPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=613,
  serialized_end=674,
)

_SPACETEAMPACKET_COMMANDPACKET = _descriptor.Descriptor(
  name='CommandPacket',
  full_name='SpaceteamPacket.CommandPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.CommandPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='panel', full_name='SpaceteamPacket.CommandPacket.panel', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='SpaceteamPacket.CommandPacket.command', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=676,
  serialized_end=766,
)

_SPACETEAMPACKET = _descriptor.Descriptor(
  name='SpaceteamPacket',
  full_name='SpaceteamPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='SpaceteamPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SPACETEAMPACKET_GAMESTATEPACKET, _SPACETEAMPACKET_CONNECTPACKET, _SPACETEAMPACKET_READYPACKET, _SPACETEAMPACKET_DISCONNECTPACKET, _SPACETEAMPACKET_COMMANDPACKET, ],
  enum_types=[
    _SPACETEAMPACKET_PACKETTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=849,
)

_SPACETEAMPACKET_GAMESTATEPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_GAMESTATEPACKET.fields_by_name['update'].enum_type = _SPACETEAMPACKET_GAMESTATEPACKET_UPDATE
_SPACETEAMPACKET_GAMESTATEPACKET.fields_by_name['screen'].enum_type = _SPACETEAMPACKET_GAMESTATEPACKET_SCREEN
_SPACETEAMPACKET_GAMESTATEPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET_GAMESTATEPACKET_UPDATE.containing_type = _SPACETEAMPACKET_GAMESTATEPACKET
_SPACETEAMPACKET_GAMESTATEPACKET_SCREEN.containing_type = _SPACETEAMPACKET_GAMESTATEPACKET
_SPACETEAMPACKET_CONNECTPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_CONNECTPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET_READYPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_READYPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET_DISCONNECTPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_DISCONNECTPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET_COMMANDPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_COMMANDPACKET.containing_type = _SPACETEAMPACKET
_SPACETEAMPACKET.fields_by_name['type'].enum_type = _SPACETEAMPACKET_PACKETTYPE
_SPACETEAMPACKET_PACKETTYPE.containing_type = _SPACETEAMPACKET
DESCRIPTOR.message_types_by_name['SpaceteamPacket'] = _SPACETEAMPACKET

SpaceteamPacket = _reflection.GeneratedProtocolMessageType('SpaceteamPacket', (_message.Message,), dict(

  GameStatePacket = _reflection.GeneratedProtocolMessageType('GameStatePacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_GAMESTATEPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.GameStatePacket)
    ))
  ,

  ConnectPacket = _reflection.GeneratedProtocolMessageType('ConnectPacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_CONNECTPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.ConnectPacket)
    ))
  ,

  ReadyPacket = _reflection.GeneratedProtocolMessageType('ReadyPacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_READYPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.ReadyPacket)
    ))
  ,

  DisconnectPacket = _reflection.GeneratedProtocolMessageType('DisconnectPacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_DISCONNECTPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.DisconnectPacket)
    ))
  ,

  CommandPacket = _reflection.GeneratedProtocolMessageType('CommandPacket', (_message.Message,), dict(
    DESCRIPTOR = _SPACETEAMPACKET_COMMANDPACKET,
    __module__ = 'spaceteam_pb2'
    # @@protoc_insertion_point(class_scope:SpaceteamPacket.CommandPacket)
    ))
  ,
  DESCRIPTOR = _SPACETEAMPACKET,
  __module__ = 'spaceteam_pb2'
  # @@protoc_insertion_point(class_scope:SpaceteamPacket)
  ))
_sym_db.RegisterMessage(SpaceteamPacket)
_sym_db.RegisterMessage(SpaceteamPacket.GameStatePacket)
_sym_db.RegisterMessage(SpaceteamPacket.ConnectPacket)
_sym_db.RegisterMessage(SpaceteamPacket.ReadyPacket)
_sym_db.RegisterMessage(SpaceteamPacket.DisconnectPacket)
_sym_db.RegisterMessage(SpaceteamPacket.CommandPacket)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005protoB\017TcpPacketProtos'))
# @@protoc_insertion_point(module_scope)
