# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timer.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0btimer.proto\"%\n\x05Timer\x12\n\n\x02id\x18\x01 \x02(\t\x12\x10\n\x08timeLeft\x18\x02 \x02(\tB\x14\n\x05protoB\x0bTimerProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TIMER = _descriptor.Descriptor(
  name='Timer',
  full_name='Timer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Timer.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeLeft', full_name='Timer.timeLeft', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Timer'] = _TIMER

Timer = _reflection.GeneratedProtocolMessageType('Timer', (_message.Message,), dict(
  DESCRIPTOR = _TIMER,
  __module__ = 'timer_pb2'
  # @@protoc_insertion_point(class_scope:Timer)
  ))
_sym_db.RegisterMessage(Timer)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005protoB\013TimerProtos'))
# @@protoc_insertion_point(module_scope)
