# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tool.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import panel_pb2 as panel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tool.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ntool.proto\x1a\x0bpanel.proto\"<\n\x04Tool\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x1a\n\npanel_list\x18\x03 \x03(\x0b\x32\x06.PanelB\x13\n\x05protoB\nToolProtos')
  ,
  dependencies=[panel__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TOOL = _descriptor.Descriptor(
  name='Tool',
  full_name='Tool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Tool.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Tool.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='panel_list', full_name='Tool.panel_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=87,
)

_TOOL.fields_by_name['panel_list'].message_type = panel__pb2._PANEL
DESCRIPTOR.message_types_by_name['Tool'] = _TOOL

Tool = _reflection.GeneratedProtocolMessageType('Tool', (_message.Message,), dict(
  DESCRIPTOR = _TOOL,
  __module__ = 'tool_pb2'
  # @@protoc_insertion_point(class_scope:Tool)
  ))
_sym_db.RegisterMessage(Tool)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005protoB\nToolProtos'))
# @@protoc_insertion_point(module_scope)
