# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udp_packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.player_pb2 as player__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='udp_packet.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x10udp_packet.proto\x1a\x0cplayer.proto\"\x93\x06\n\tUdpPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x1aM\n\rConnectPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x17\n\x06player\x18\x02 \x01(\x0b\x32\x07.Player\x1av\n\x10\x43reateRoomPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x0f\n\x07room_id\x18\x02 \x01(\t\x12\x13\n\x0bmax_players\x18\x03 \x01(\x05\x12\x17\n\x06player\x18\x04 \x02(\x0b\x32\x07.Player\x1aK\n\x0bLeavePacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x17\n\x06player\x18\x02 \x01(\x0b\x32\x07.Player\x1a`\n\nJoinPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x1c\n\x0bplayer_list\x18\x02 \x02(\x0b\x32\x07.Player\x12\x0f\n\x07room_id\x18\x03 \x01(\t\x1aU\n\x10PlayerListPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x1c\n\x0bplayer_list\x18\x02 \x03(\x0b\x32\x07.Player\x1aJ\n\x0e\x45rrLfullPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x13\n\x0b\x65rr_message\x18\x02 \x01(\t\x1a\x45\n\tErrPacket\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.UdpPacket.PacketType\x12\x13\n\x0b\x65rr_message\x18\x02 \x01(\t\"\x80\x01\n\nPacketType\x12\x0b\n\x07\x43ONNECT\x10\x00\x12\x0f\n\x0b\x43REATE_ROOM\x10\x01\x12\t\n\x05LEAVE\x10\x02\x12\x08\n\x04JOIN\x10\x03\x12\x08\n\x04PLAY\x10\x04\x12\x0f\n\x0bPLAYER_LIST\x10\x05\x12\x0c\n\x08\x45RR_RDNE\x10\x06\x12\r\n\tERR_RFULL\x10\x07\x12\x07\n\x03\x45RR\x10\x08\x42\x18\n\x05protoB\x0fUdpPacketProtos')
  ,
  dependencies=[player__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_UDPPACKET_PACKETTYPE = _descriptor.EnumDescriptor(
  name='PacketType',
  full_name='UdpPacket.PacketType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_ROOM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEAVE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JOIN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_LIST', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_RDNE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_RFULL', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR', index=8, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=694,
  serialized_end=822,
)
_sym_db.RegisterEnumDescriptor(_UDPPACKET_PACKETTYPE)


_UDPPACKET_CONNECTPACKET = _descriptor.Descriptor(
  name='ConnectPacket',
  full_name='UdpPacket.ConnectPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.ConnectPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='UdpPacket.ConnectPacket.player', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=162,
)

_UDPPACKET_CREATEROOMPACKET = _descriptor.Descriptor(
  name='CreateRoomPacket',
  full_name='UdpPacket.CreateRoomPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.CreateRoomPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='UdpPacket.CreateRoomPacket.room_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_players', full_name='UdpPacket.CreateRoomPacket.max_players', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='UdpPacket.CreateRoomPacket.player', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=282,
)

_UDPPACKET_LEAVEPACKET = _descriptor.Descriptor(
  name='LeavePacket',
  full_name='UdpPacket.LeavePacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.LeavePacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='UdpPacket.LeavePacket.player', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=359,
)

_UDPPACKET_JOINPACKET = _descriptor.Descriptor(
  name='JoinPacket',
  full_name='UdpPacket.JoinPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.JoinPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_list', full_name='UdpPacket.JoinPacket.player_list', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='UdpPacket.JoinPacket.room_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=457,
)

_UDPPACKET_PLAYERLISTPACKET = _descriptor.Descriptor(
  name='PlayerListPacket',
  full_name='UdpPacket.PlayerListPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.PlayerListPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_list', full_name='UdpPacket.PlayerListPacket.player_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=544,
)

_UDPPACKET_ERRLFULLPACKET = _descriptor.Descriptor(
  name='ErrLfullPacket',
  full_name='UdpPacket.ErrLfullPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.ErrLfullPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err_message', full_name='UdpPacket.ErrLfullPacket.err_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=546,
  serialized_end=620,
)

_UDPPACKET_ERRPACKET = _descriptor.Descriptor(
  name='ErrPacket',
  full_name='UdpPacket.ErrPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.ErrPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err_message', full_name='UdpPacket.ErrPacket.err_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=691,
)

_UDPPACKET = _descriptor.Descriptor(
  name='UdpPacket',
  full_name='UdpPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='UdpPacket.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_UDPPACKET_CONNECTPACKET, _UDPPACKET_CREATEROOMPACKET, _UDPPACKET_LEAVEPACKET, _UDPPACKET_JOINPACKET, _UDPPACKET_PLAYERLISTPACKET, _UDPPACKET_ERRLFULLPACKET, _UDPPACKET_ERRPACKET, ],
  enum_types=[
    _UDPPACKET_PACKETTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=822,
)

_UDPPACKET_CONNECTPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_CONNECTPACKET.fields_by_name['player'].message_type = player__pb2._PLAYER
_UDPPACKET_CONNECTPACKET.containing_type = _UDPPACKET
_UDPPACKET_CREATEROOMPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_CREATEROOMPACKET.fields_by_name['player'].message_type = player__pb2._PLAYER
_UDPPACKET_CREATEROOMPACKET.containing_type = _UDPPACKET
_UDPPACKET_LEAVEPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_LEAVEPACKET.fields_by_name['player'].message_type = player__pb2._PLAYER
_UDPPACKET_LEAVEPACKET.containing_type = _UDPPACKET
_UDPPACKET_JOINPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_JOINPACKET.fields_by_name['player_list'].message_type = player__pb2._PLAYER
_UDPPACKET_JOINPACKET.containing_type = _UDPPACKET
_UDPPACKET_PLAYERLISTPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_PLAYERLISTPACKET.fields_by_name['player_list'].message_type = player__pb2._PLAYER
_UDPPACKET_PLAYERLISTPACKET.containing_type = _UDPPACKET
_UDPPACKET_ERRLFULLPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_ERRLFULLPACKET.containing_type = _UDPPACKET
_UDPPACKET_ERRPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_ERRPACKET.containing_type = _UDPPACKET
_UDPPACKET.fields_by_name['type'].enum_type = _UDPPACKET_PACKETTYPE
_UDPPACKET_PACKETTYPE.containing_type = _UDPPACKET
DESCRIPTOR.message_types_by_name['UdpPacket'] = _UDPPACKET

UdpPacket = _reflection.GeneratedProtocolMessageType('UdpPacket', (_message.Message,), dict(

  ConnectPacket = _reflection.GeneratedProtocolMessageType('ConnectPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_CONNECTPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.ConnectPacket)
    ))
  ,

  CreateRoomPacket = _reflection.GeneratedProtocolMessageType('CreateRoomPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_CREATEROOMPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.CreateRoomPacket)
    ))
  ,

  LeavePacket = _reflection.GeneratedProtocolMessageType('LeavePacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_LEAVEPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.LeavePacket)
    ))
  ,

  JoinPacket = _reflection.GeneratedProtocolMessageType('JoinPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_JOINPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.JoinPacket)
    ))
  ,

  PlayerListPacket = _reflection.GeneratedProtocolMessageType('PlayerListPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_PLAYERLISTPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.PlayerListPacket)
    ))
  ,

  ErrLfullPacket = _reflection.GeneratedProtocolMessageType('ErrLfullPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_ERRLFULLPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.ErrLfullPacket)
    ))
  ,

  ErrPacket = _reflection.GeneratedProtocolMessageType('ErrPacket', (_message.Message,), dict(
    DESCRIPTOR = _UDPPACKET_ERRPACKET,
    __module__ = 'udp_packet_pb2'
    # @@protoc_insertion_point(class_scope:UdpPacket.ErrPacket)
    ))
  ,
  DESCRIPTOR = _UDPPACKET,
  __module__ = 'udp_packet_pb2'
  # @@protoc_insertion_point(class_scope:UdpPacket)
  ))
_sym_db.RegisterMessage(UdpPacket)
_sym_db.RegisterMessage(UdpPacket.ConnectPacket)
_sym_db.RegisterMessage(UdpPacket.CreateRoomPacket)
_sym_db.RegisterMessage(UdpPacket.LeavePacket)
_sym_db.RegisterMessage(UdpPacket.JoinPacket)
_sym_db.RegisterMessage(UdpPacket.PlayerListPacket)
_sym_db.RegisterMessage(UdpPacket.ErrLfullPacket)
_sym_db.RegisterMessage(UdpPacket.ErrPacket)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005protoB\017UdpPacketProtos'))
# @@protoc_insertion_point(module_scope)
